<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

// Defers Alpine.js initialisation, while preserving the rendering of all child elements.
?>
<?= $block->getChildHtml() ?>
