<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\App\State as ApplicationState;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$id = $block->getNameInLayout() ?? '';

$state = $block->getData('application_state');
$exception = $block->getData('exception');
?>
<?php if ($state instanceof ApplicationState && $state->getMode() === ApplicationState::MODE_DEVELOPER): ?>
<div class="magewire-exception">
    <pre class="magewire-exception-trace">
        <span class="magewire-exception-label">Exception:</span> <?= $escaper->escapeHtml($exception->getMessage()) ?>
    </pre>

    <p class="magewire-exception-message">
        <?php if (strlen($id) === 0): ?>
            <?= $escaper->escapeHtml(__('An exception occurred while parsing and/or rendering the Magewire component.')) ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('An exception occurred while parsing and/or rendering the Magewire component associated with a block named: %1.', $id)) ?>
        <?php endif ?>
    </p>
</div>
<?php endif ?>

<?php if (strlen($id) === 0): ?>
    <!-- Magewire exception: <?= $escaper->escapeHtml($id) ?> -->
<?php else: ?>
    <!-- Magewire exception -->
<?php endif ?>
