<script>
    function magewireLoaderNotifications(config = {}) {
        return {
            messages: [],
            awaiting: [], // wip

            config: Object.assign({
                messageHideTimeout: 2500,
                messageHideTimeoutCalculation: false,
            }, config),

            init() {
                <?php /* @see Magewirephp_Magewire::page/js/magewire/plugin/loader.phtml */ ?>
                document.addEventListener('magewire:loader:start', (event) => {
                    this.messageCreate(event.detail);
                })

                <?php /* @see Magewirephp_Magewire::page/js/magewire/plugin/loader.phtml */ ?>
                document.addEventListener('magewire:loader:stop', (event) => {
                    if (! event.detail.component && ! event.detail.component.id && event.detail.loader) return;

                    <?php /* Find the component by its unique key to try and deactivate it. */ ?>
                    for (let message in this.messages) {
                        if (event.detail.loader && this.messages[message].key == event.detail.loader.key) {
                            return this.messageDeactivate(message, event.failure || false);
                        }
                    }
                })
            },

            <?php /* Create a new message an determine if it needs to be shown or should wait. */ ?>
            messageCreate(item) {
                if (! event.detail.loader) return;

                item.loader.map(i => i.split('::')).forEach((value, index) => {
                    let message = Object.assign({}, item, {
                        <?php /* Can only be of type Boolean. */ ?>
                        active : false,
                        <?php /* Can be of value Array or Boolean. */ ?>
                        loader : value,
                        <?php /* Can only be of type Boolean. */ ?>
                        loading: false,
                        <?php /* Can be of value null, true or false. */ ?>
                        success: null
                    });

                    if (index === 0) {
                        message.active  = true;
                        message.loading = true;

                        this.messages.push(message);
                    } else {
                        this.awaiting.push(message);
                    }
                });
            },

            <?php /* Deactivate message, but not remove it fully from the array to let animations run. */ ?>
            messageDeactivate(index, failure = false) {
                message = this.messages[index] || false;

                if (message === false) {
                    return console.error('Magewire: Could not deactivate the notification message.');
                }

                message.loading = false;
                message.success = ! failure;

                let timeout = this.config.messageHideTimeout;

                if (this.config.messageHideTimeoutCalculation) {
                    timeout += (Math.floor(
                        message.loader.reduce((total, str) => (total + str.length), 0) / 10) * (message.loader.length * 100)
                    );
                }

                if (failure) {
                    timeout + 5000;
                }

                setTimeout(() => message.active = false, timeout);
            },

            messageList() {
                return this.messages.filter(message => message.loader.length)
            },

            notifications() {
                return {}
            },

            messenger() {
                return {}
            }
        }
    }
</script>
