<script nonce="<?= /* @noEscape */ $this->helper(\Magewirephp\Magewire\Helper\CspNonceProvider::class)->generateNonce() ?>">
    function magewireLoader() {
        return {
            active: false,

            loader() {
                return {
                    ['x-on:magewire:loader:start.window']() {
                        this.active = true
                    },
                    ['x-on:magewire:loader:done.window']() {
                        this.active = false
                    },
                    ['x-bind:class']() {
                        return {
                            'z-50 relative': this.active
                        };
                    }
                };
            },

            overlay() {
                return {
                    ['x-show']() {
                        return this.active;
                    }
                };
            },

            componentOverlay() {
                return {
                    ['x-init']() {
                        Magewire.hook('message.sent', (message, component) => {
                            const componentOverlayElement = document.getElementById('magewire-loader-component-overlay')

                            if (! component.el.classList.contains('relative')) {
                                component.el.classList.add('relative')
                            }

                            component.el.appendChild(componentOverlayElement.content.cloneNode(true))
                        })
                    }
                }
            }
        };
    }
    (() => {
        const initFn = () => Alpine.data('magewireLoader', magewireLoader);
        window.Alpine ? initFn() : window.addEventListener('alpine:init', initFn, {once: true})
    })()
</script>
