<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

/** @var Template $block */
/** @var Magewire $magewireScripts */

$magewireScripts = $block->getViewModel();
?>
<script<?= /* @noEscape */ $magewireScripts->csp()->generateNonceAttribute() ?>>
    function magewireLoader() {
        return {
            active: false,

            loader() {
                return {
                    ['x-on:magewire:loader:start.window']() {
                        this.active = true
                    },
                    ['x-on:magewire:loader:done.window']() {
                        this.active = false
                    },
                    ['x-bind:class']() {
                        return {
                            'z-50 relative': this.active
                        };
                    }
                };
            },

            overlay() {
                return {
                    ['x-show']() {
                        return this.active;
                    }
                };
            },

            componentOverlay() {
                return {
                    ['x-init']() {
                        Magewire.hook('message.sent', (message, component) => {
                            const componentOverlayElement = document.getElementById('magewire-loader-component-overlay')

                            if (! component.el.classList.contains('relative')) {
                                component.el.classList.add('relative')
                            }

                            component.el.appendChild(componentOverlayElement.content.cloneNode(true))
                        })
                    }
                }
            }
        };
    }

    (() => {
        const initFn = () => Alpine.data('magewireLoader', magewireLoader);
        window.Alpine ? initFn() : window.addEventListener('alpine:init', initFn, {once: true})
    })()
</script>
