<script>
    function magewireLoader() {
        return {
            active: false,

            loader() {
                return {
                    ['x-on:magewire:loader:start.window']() {
                        this.active = true
                    },
                    ['x-on:magewire:loader:fail.window']() {
                        this.active = false
                    },
                    ['x-on:magewire:loader:stop.window']() {
                        this.active = false
                    },
                    ['x-bind:class']() {
                        return {
                            'z-50 relative': this.active
                        };
                    }
                };
            },

            overlay() {
                return {
                    ['x-show']() {
                        return this.active;
                    }
                };
            }
        };
    }
</script>
