<script>
    function magewireLoader() {
        return {
            active: false,
            notifications: [],
            current: 0,

            wrapper() {
                return {
                    ['x-on:magewire:loader:start.window']() {
                        this.active = true

                        if (this.$event.detail) {
                            this.notifications.push(Object.assign(this.$event.detail, { active: true, show: true, failed: false }))
                            this.current = this.$event.detail.title ? this.notifications.length - 1 : this.current
                        }
                    },
                    ['x-on:magewire:loader:tick.window']() {
                        if (this.notifications[this.current] !== undefined) {
                            this.notifications[this.current].active = false
                        }

                        if (this.$event.detail) {
                            this.notifications.push(Object.assign(this.$event.detail, { active: true, show: true, failed: false }))
                            this.current = this.$event.detail.title ? this.notifications.length - 1 : this.current
                        }
                    },
                    ['x-on:magewire:loader:fail.window']() {
                        if (this.notifications[this.current] !== undefined) {
                            this.notifications[this.current].failed = true
                        }
                    },
                    ['x-on:magewire:loader:stop.window']() {
                        if (this.notifications[this.current]) {
                            this.notifications[this.current].active = false
                        }

                        this.active = false
                        this.current = null

                        let delay = 0

                        this.notifications.forEach((notification) => {
                            console.log(notification)
                            if (! notification.title || ! notification.show) {
                                return
                            }

                            // todo: the issue here is if you have two or more labels in the loader.title, it will use
                            //       the same object when you click the action again. So when the active label is still
                            //       on e.g. the second label, the second loader will also start the second loader label
                            if (notification.title.length === 2) {

                                notification.title.reverse()
                                delay += 1000

                            }

                            setTimeout(() => {
                                notification.show = false
                            }, delay += notification.failed ? 2500 : 1500)
                        })
                    },
                    ['x-bind:class']() {
                        return {
                            'z-50 relative': this.active
                        }
                    }
                }
            },

            loader() {
                return {
                    ['x-show']() {
                        return this.active
                    }
                }
            }
        }
    }
</script>
