<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

/** @var Escaper $escaper */
/** @var Template $block */

?>
<div <?php /* AlpineJS v2.x */ ?>
     x-spread="componentOverlay"
     <?php /* AlpineJS v3.x */ ?>
     x-bind="componentOverlay"
     role="status"
     aria-live="polite"
>
    <template id="magewire-loader-component-overlay" x-ref="overlay">
        <div class="absolute -inset-4 grid cursor-wait place-items-center">
            <div class="w-14 h-14 p-3 bg-white/90 rounded-full flex items-center justify-center shadow-md">
                <div class="w-8 h-8">
                    <?= $block->getChildHtml('spinner') ?>
                </div>
            </div>
        </div>
    </template>
</div>
