<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var Template $block */

$magewireScripts = $block->getViewModel();
$magewireConfig = $magewireScripts->getSystemConfig();
?>
<div id="magewire-loader-notifications"
     x-data="magewireLoaderNotifications"
     data-config="<?= $escaper->escapeHtmlAttr(json_encode(['messageHideTimeout' => $magewireConfig->getNotificationMessageFadeoutTimeout()])) ?>"
     x-init="initialize"
     <?php /* AlpineJS v2.x */ ?>
     x-spread="notifications"
     <?php /* AlpineJS v3.x */ ?>
     x-bind="notifications"
>
    <?= $block->getChildHtml('messenger') ?>
</div>

<?php /* Write your own loader notifications implementation without having to rewrite all the AlpineJS. */ ?>
<?= $block->getChildHtml('bindings') ?>
