<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
?>
<div id="magewire-loader-notifications"
     x-data="magewireLoaderNotifications()"
     <?php /* AlpineJS v2.x */ ?>
     x-spread="notifications"
     <?php /* AlpineJS v3.x */ ?>
     x-bind="notifications"
>
    <?= $block->getChildHtml('messenger') ?>
</div>

<?php /* Write your own loader notifications implementation without having to rewrite all the AlpineJS. */ ?>
<?= $block->getChildHtml('bindings') ?>
