<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<div class="fixed
            top-0 left-0 right-0 bottom-0
            w-full h-screen
            overflow-hidden
            bg-white bg-opacity-90"
     <?php /* AlpineJS v2.x */ ?>
     x-spread="overlay"
     <?php /* AlpineJS v3.x */ ?>
     x-bind="overlay"
     x-transition:enter="transition duration-300"
     x-transition:enter-start="opacity-0"
     x-transition:enter-end="opacity-100"
     x-transition:leave="transition duration-200"
     x-transition:leave-start="opacity-100"
     x-transition:leave-end="opacity-0"
>
    <div class="flex flex-col justify-center items-center h-screen w-full space-y-6">
        <?= $block->getChildHtml('spinner') ?>
    </div>
</div>
