<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

use Magento\Framework\App\State;
use Magento\Framework\View\Element\Template;

/** @var $block Template */
?>
<?php if ($block->getApplicationState()->getMode() === State::MODE_DEVELOPER): ?>
<div class="magewire-exception">
    <pre class="whitespace-pre-line text-sm text-gray-600 border rounded border-gray-600 p-4">
        <span class="text-red-600 font-bold">Exception:</span> <?= $block->getException()->getMessage() ?>
    </pre>

    <p class="text-xs mt-2">This exception was thrown while parsing and/or rendering the Magewire component with block name "<?= $block->getNameInLayout() ?>".</p>
</div>
<?php endif; ?>
<!-- Magewire Component wire-exception: <?= $block->getNameInLayout() ?>-->

