<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */
?>
<?php if ($block->getApplicationState()->getMode() === \Magento\Framework\App\State::MODE_DEVELOPER): ?>
<div class="overflow-x-auto">
    <pre class="whitespace-nowrap text-xs">
        <?= $block->getException()->getMessage() ?>
    </pre>
</div>
<?php else: ?>
<p>Something went wrong. Please try again later.</p>
<?php endif; ?>
