<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var Magewire $magewireScripts */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $viewModels->require(Magewire::class);
?>
<?php if ($magewireScripts->pageRequiresMagewire()): ?>
<script>
    'use strict';

    if (window.magewire) {
        console.warn('Magewire: It looks like Magewire\'s JavaScript assets have already been loaded. Make sure you aren\'t loading them twice.')
    }

    window.magewire = new Livewire()
    <?php if ($magewireScripts->isDeveloperMode()): ?>
    window.magewire.devTools(true)
    <?php endif; ?>

    window.Livewire = window.magewire
    window.Magewire = window.magewire
    window.livewire_app_url = '<?= $escaper->escapeUrl($magewireScripts->getApplicationUrl()) ?>'
    window.livewire_token = window.hyva.getFormKey()

    <?php /* Make sure Magewire loads first. */ ?>
    if (window.Alpine) {
        <?php /* Defer showing the warning so it doesn't get buried under downstream errors. */ ?>
        document.addEventListener("DOMContentLoaded", () => {
            setTimeout(function() {
                console.warn("Magewire: It looks like AlpineJS has already been loaded. Make sure Magewire\'s scripts are loaded before AlpineJS.")
            })
        })
    }

    <?php /* Initialize Alpine after Magewire */ ?>
    (() => {
        <?php /* At this time Alpine is not yet loaded, so it is impossible to check how to defer Alpine initialization. */ ?>
        const startMagewireOnce = () => {
            document.removeEventListener('DOMContentLoaded', startMagewireOnce);
            window.removeEventListener('alpine:init', startMagewireOnce);
            window.magewire.start();
        }

        <?php /* Initialize Alpine v2 after Magewire */ ?>
        const initAlpine = window.deferLoadingAlpine || ((callback) => callback());
        window.deferLoadingAlpine = (callback) => {
            window.addEventListener('magewire:load', () => {
                initAlpine(callback)
            });
        }
        document.addEventListener('DOMContentLoaded', startMagewireOnce)

        <?php /* Init Alpine v3 after Magewire */ ?>
        <?php /* (Note: with v3 alpine:init is dispatched before DOMContentLoaded. In v2 it is not used) */ ?>
        window.addEventListener('alpine:init', startMagewireOnce);
    })();

    <?php /* Dispatch "magewire:" prefixed window events. */ ?>
    Magewire.dispatchEvent = (name, event = {}) => {
        document.dispatchEvent(new CustomEvent(`magewire:${ name }`, Object.assign({
            'bubbles': true,
            'cancelable': false
        }, event)))
    }

    <?php /* Mirror Livewire events. */ ?>
    ['load', 'update'].forEach(function (target, index) {
        document.addEventListener('livewire:' + target, (event) => {
            Magewire.dispatchEvent(target, event)
        })
    })

    <?php /* Allow component.initialize hooks to be registered before the components are initialized */ ?>
    Magewire.dispatchEvent('available');
</script>

    <?= /* @noEscape */ $block->getChildHtml('magewire.plugins') ?>
<?php endif ?>
