<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 *
 * ----------------------------- <3 -----------------------------
 * @version 2.10.5
 * @author Caleb Porzio (Laravel Livewire)
 * @link https://laravel-livewire.com/
 *
 * @var Escaper $escaper
 * @var AbstractBlock $block
 * @var Magewire $magewireScripts
 * @var ViewModelRegistry $viewModels
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $viewModels->require(Magewire::class);
?>
<?php if ($magewireScripts->pageRequiresMagewire()): ?>
<script>
    document.addEventListener('livewire:available', (event) => {
        document.dispatchEvent(new Event('magewire:available', {
            'bubbles': event.bubbles || true,
            'cancelable': event.cancelable || true
        }))
    })
</script>

<script src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magewirephp_Magewire::js/livewire.js')) ?>"></script>
<?php endif ?>