<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

/** @var \Magewirephp\Magewire\Magewire\Playwright\Events\Basic $magewire */
?>
<div data-testid="events-component">
    <p data-testid="event-result"><?= $escaper->escapeHtml($magewire->result) ?></p>
</div>
