<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getViewModel();
$messages = $block->getData('status_messages');
?>
<script nonce="<?= /* @noEscape */ $this->helper(\Magewirephp\Magewire\Helper\CspNonceProvider::class)->generateNonce() ?>">
    'use strict';

    Magewire.onPageExpired(() => {
        alert('<?= $escaper->escapeJs(__($messages[419] ?? 'Your session has expired due to inactivity.')) ?>')
        window.location.reload()
    })

    Magewire.onError((status, response) => {
        <?php /* We need to make sure Magewire reaches the native 419 handling. */ ?>
        if (status === 419) {
            return
        }

        <?php if ($magewireScripts->isProductionMode()): ?>
        response.clone().text().then((result) => {
            let messages = <?= /** @noEscape */ json_encode(array_map('__', $messages)) ?>;
            result = JSON.parse(result)

            console.error(
                `Magewire: ${ messages[status] || result.message || 'Something went wrong' } (${ status })`
            )
        }).catch((exception) => {
            console.error(exception)
        })

        return false
        <?php endif ?>
    })
</script>

