<?php declare(strict_types=1);
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getViewModel();
$messages = $block->getData('status_messages');
?>
<?php if ($magewireScripts->isProductionMode()): ?>
    <script>
        'use strict';

        Magewire.onError((status, response) => {
            if (status === 419) {
                alert('<?= $escaper->escapeJs(__($messages[419] ?? 'The session has expired.')) ?>')
                window.location.reload()

                return false
            }

            response.text().then((result) => {
                let messages = <?= /** @noEscape */ json_encode(array_map('__', $messages)) ?>
                result = JSON.parse(result)

                console.error(
                    `Magewire: ${ messages[status] || result.message || 'Something went wrong' } (${ status })`
                )
            }).catch((exception) => {
                console.error(exception)
            })

            return false
        })
    </script>
<?php endif ?>
