<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Model\Action\CallMethod;
use Magewirephp\Magewire\Model\Action\FireEvent;
use Magewirephp\Magewire\Model\Action\SyncInput;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getViewModel();
?>
<?php if ($magewireScripts->pageRequiresMagewire() && $magewireScripts->getSystemConfig()->pageRequiresLoaderPluginScript()): ?>
    <script>
        'use strict';

        (() => {
            <?php /* Active loaders queue. */ ?>
            let queue = [];

            const loaderTypeResolvers = {
                <?= /** @noEscape */ SyncInput::ACTION ?>: (item, loader) => {
                    let name = item.payload.name;

                    let expression = [
                        `${ name }:${ item.payload.value }`,
                        `${ name.substr(0, name.lastIndexOf('.')) }:${ item.payload.value }`,
                        `${ name }`,
                        `${ name.substr(0, name.lastIndexOf('.')) }`
                    ].filter((expression) => {
                        return expression in loader
                    })[0] || false;

                    if (expression) {
                        return loader[expression];
                    }

                    return true;
                },
                <?= /** @noEscape */ CallMethod::ACTION ?>: (item, loader) => {
                    return loader[item.method];
                },
                <?= /** @noEscape */ FireEvent::ACTION ?>: (item, loader) => {
                    return loader[item.payload.event];
                }
            }

            const getLoaderData = function(message, component) {
                let loader = component.effects.loader || null;

                if (! loader) {
                    return null;
                }

                let data = {};

                for (let item of message.updateQueue) {
                    let value = true;

                    if (typeof loader === 'object' && item.type in loaderTypeResolvers) {
                        value = loaderTypeResolvers[item.type](item, loader);
                    } else if (typeof loader === 'string') {
                        value = [loader];
                    }

                    if (value === undefined) {
                        value = false;

                        <?php /* Include wildcard support. */ ?>
                        if ('*' in loader) {
                            value = loader['*'];
                        }
                    }

                    data[component.id] = {
                        key: Date.now(),
                        component: component,
                        loader: value,
                        update: item
                    };
                }

                return data;
            }

            const start = function(loader, component) {
                let first = ! queue.some(({ parent }) => parent);
                let me = queue.findIndex(item => item.component.id === component.id);

                if (first) {
                    queue.push({
                        loader: loader,
                        component: component
                    });
                }

                <?php /* Sprinkle in the missing loader when this item was added from elsewhere without */ ?>
                <?php /* knowing what the loader value is gonna be at that point in the lifecycle. */ ?>
                if (queue[me]) {
                    queue[me].loader = loader;
                }

                queue.forEach((item, index) => {
                    item.parent = item.parent ?? false;

                    <?php /* Lets find out which loader was already active before me and force it to stop. */ ?>
                    if (me > index && item.loader) {
                        stop(item.component, false, true);
                    }
                });

                Magewire.dispatchEvent(`loader:${ first ? 'start' : 'tick' }`, {
                    detail: loader
                });
            }

            <?php /* TODO: both methods are kinda the same and they should merge into one with an addition arguments. */ ?>
            <?php /*       going for a let queue = [...queue].reverse() could be a good option for the 'after'. */ ?>
            const everythingBeforeMe = function(component) {
                let me = queue.findIndex(item => item.component.id === component.id);
                let before = [];

                if (me > 0) {
                    for (let i = queue.length - 1; i >= 0; i--) {
                        if (component && queue[i] && queue[i].component && queue[i].component.id !== component.id) {
                            before.push(i);
                        }
                    }
                }

                return before;
            }

            const everythingAfterMe = function(component) {
                let me = queue.findIndex(item => item.component.id === component.id);
                let after = [];

                if (me > 0) {
                    for (let i = me + 1; i < queue.length; i++) {
                        if (component && queue[i] && queue[i].component && queue[i].component.id !== component.id) {
                            after.push(i);
                        }
                    }
                }

                return after;
            }

            const stop = function(component, failure = false, force = false) {
                if (failure) {
                    force = true;
                }

                <?php /* Queue items targeted to remove. */ ?>
                let remove = [];
                <?php /* Get my own index. */ ?>
                let me = queue.findIndex(item => item.component.id === component.id);
                <?php /* Store the last queue item index. */ ?>
                let last = queue.length - 1;

                if (me === last) {
                    if (queue[me].loader) {
                        force = true;
                    } else {
                        remove.push(me);
                    }

                    <?php /* Since I'm the last in line, everything before me can go. */ ?>
                    everythingBeforeMe(component).forEach(key => remove.push(key));
                }

                if (force) {
                    if (me < last) {
                        let proceed = true;

                        everythingAfterMe(component).forEach(index => {
                            if (queue[index].loader) {
                                proceed = false;
                            }
                            if (proceed) {
                                remove.push(index);
                            }
                        });
                    }

                    remove.push(me);
                }

                <?php /* Run over the queue and remove those who are marked. In the meanwhile, when we hit */ ?>
                <?php /* a item which seems to have a loader, it should stop itself. */ ?>
                remove.forEach(index => {
                    if (queue[index]) {
                        if (queue[index].loader) {
                            Magewire.dispatchEvent(`loader:stop`, {
                                detail: {
                                    loader: queue[index].loader,
                                    component: queue[index].component,
                                    failure: failure
                                }
                            });
                        }

                        delete queue[index];
                    }
                });

                // Refresh queue.
                queue = Object.values(queue);

                if (queue.length === 0) {
                    Magewire.dispatchEvent(`loader:done`, {
                        detail: {
                            component: component,
                            failure: failure
                        }
                    });

                    // Reset queue with a fresh array.
                    queue = [];
                }
            }

            <?php /* Magewire loader plugin registration. */ ?>
            Magewire.plugins.loader = (() => {
                return {
                    start(loader, component) {
                        return start(loader, component);
                    },
                    stop(component, failure = false, force = false) {
                        return stop(component, failure, force);
                    }
                }
            })();

            document.addEventListener('DOMContentLoaded', () => {
                Magewire.hook('message.sent', (message, component) => {
                    let loader = getLoaderData(message, component) || {};

                    if (component.id in loader && loader[component.id].loader) {
                        Magewire.plugins.loader.start(loader[component.id], component);
                    }
                });

                Magewire.hook('message.processed', (message, component) => {
                    if (message.response && message.response.effects) {
                        (message.response.effects.emits || []).forEach((emit) => {
                            Magewire.components.componentsListeningForEvent(emit.event)
                                .filter(listener => ! emit.to || emit.to === listener.id)
                                .forEach(listener => queue.push({ component: listener, parent: component }));
                        });
                    }

                    Magewire.plugins.loader.stop(component);

                    <?php /* Re-assign optional new dynamic loader values. */ ?>
                    if (component.effects && message.response.effects) {
                        component.effects.loader = message.response.effects.loader;
                    }
                });

                Magewire.hook('message.failed', (message, component) => {
                    Magewire.plugins.loader.stop(component, true);
                });
            });
        })();
    </script>
<?php endif ?>
