<script defer>
    'use strict';

    (() => {
        document.addEventListener('DOMContentLoaded', () => {
            let emitsAreAvailable = false

            const grepLoaderData = (message, component) => {
                if ('loader' in component.effects ) {
                    let data = {}

                    for (let item of message.updateQueue) {
                        if (typeof component.effects.loader === 'object') {
                            data[component.id] = Object.assign(item, {
                                title: component.effects.loader[item.method]
                            })
                        } else if (component.effects.loader === true) {
                            data[component.id] = Object.assign(item, {
                                title: null
                            })
                        }
                    }

                    return data
                }

                return null
            }

            Magewire.hook('message.sent', (message, component) => {
                let loaderData = grepLoaderData(message, component) ?? {}

                if (component.id in loaderData || emitsAreAvailable) {
                    emitsAreAvailable = false
                    loaderData = component.id in loaderData ? loaderData[component.id] : null

                    Magewire.dispatchEvent('loader:start', {
                        detail: {
                            message: message,
                            component: component,
                            loader: loaderData
                        }
                    })
                }
            })

            Magewire.hook('message.processed', (message, component) => {
                emitsAreAvailable = 'loader' in component.effects && 'emits' in message.response.effects

                Magewire.dispatchEvent('loader:stop', {
                    detail: {
                        message: message,
                        component: component
                    }
                })
            })

            Magewire.hook('message.failed', (message, component) => {
                Magewire.dispatchEvent('loader:stop', {
                    detail: {
                        message: message,
                        component: component
                    }
                })
            })
        })
    })();
</script>
