<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

/** @var Template $block */
/** @var Magewire $magewireScripts */

use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire;
?>
<script<?= /* @noEscape */ $magewireScripts->csp()->generateNonceAttribute() ?>>
    Magewire.hasPlugin = function(name) {
        const plugins = Magewire.plugins

        if (typeof plugins !== 'object' || plugins.length === 0) {
            return false;
        } else if (typeof name === 'object') {
            return name.every((name) => Magewire.hasPlugin(name))
        }

        return name in plugins
    }
</script>
