<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var MagewireViewModel $magewireViewModel */

$magewireViewModel = $block->getData('view_model');
$magewireUtility = $magewireViewModel->utils()->magewire();
$magewireTemplateFragment = $magewireViewModel->utils()->template()->fragment();
?>
<?php $script = $magewireTemplateFragment->script()->start() ?>
<script>
    function magewireScript() {
        return {

        }
    }

    <?php /* Register as Alpine component. */ ?>
    document.addEventListener('alpine:init', () => Alpine.data('magewireScript', magewireScript), { once: true })
</script>
<?php $script->end() ?>
