<?php
/**
 * @author Hyvä Themes <info@hyva.io>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Hyva\CheckoutCore\ViewModel\Page\Loader as LoaderViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$loader = $viewModels->require(LoaderViewModel::class);
?>
<div id="magewire-loader"
     class="flex flex-col
            fixed
            top-0 left-0 right-0 bottom-0
            w-full h-screen
            z-50
            overflow-hidden
            bg-white bg-opacity-90
            items-center justify-center"
     x-data="{ visible: false, title: null, loader: {} }"
     x-show="visible"
     x-on:magewire:loader:start.window="visible = true; title = $event.detail.title || loader.title; loader = $event.detail"
     x-on:magewire:loader:stop.window="visible = false; title = null; loader = $event.detail"
     x-transition:enter="transition ease-out duration-300"
     x-transition:enter-start="opacity-0"
     x-transition:enter-end="opacity-100"
     x-transition:leave="transition ease-in duration-300"
     x-transition:leave-start="opacity-100"
     x-transition:leave-end="opacity-0"
     x-cloak
     role="status"
>
    <svg class="animate-spin h-8 w-8 text-green-700"
         xmlns="http://www.w3.org/2000/svg"
         fill="none"
         viewBox="0 0 24 24"
    >
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4">test</circle>
        <path class="shadow-md" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>

    <div class="h-12">
        <div class="mt-4 font-bold text-sm text-gray-800"
             x-show="title !== null"
             x-text="title"
             x-transition:enter="transition duration-300"
             x-transition:enter-start="opacity-0 transform -translate-y-6"
             x-transition:enter-end="opacity-100 transform translate-y-0"
             x-transition:leave="transition ease-in duration-300"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
        >
            <!-- Magewire: Title Placeholder -->
        </div>
    </div>
</div>
