<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var \Magewirephp\Magewire\ViewModel\Magewire $magewireScripts */

$magewireScripts = $block->getViewModel();
$magewireSystemConfig = $magewireScripts->getSystemConfig();
?>
<?php if ($magewireScripts->pageRequiresMagewire()): ?>
    <div id="magewire-loader"
         x-data="magewireLoader()"
         <?php /* AlpineJS v2.x */ ?>
         x-spread="loader()"
         <?php /* AlpineJS v3.x */ ?>
         x-bind="loader()"
         role="status"
         aria-live="polite"
    >
        <?= $block->getChildHtml($magewireSystemConfig->getLoaderOverlay()) ?>
        <?= $block->getChildHtml('notifications') ?>
    </div>

    <?php /* Write your own loader implementation without having to rewrite all the AlpineJS. */ ?>
    <?= $block->getChildHtml('bindings') ?>
<?php endif ?>
