<?php
/**
 * @author Hyvä Themes <info@hyva.io>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
$magewireScripts = $block->getViewModel();
?>
<?php if ($magewireScripts->pageRequiresMagewire()): ?>
<div id="magewire-loader"
     x-data="{
         active: false,
         notifications: [],
         current: 0
     }"
     x-on:magewire:loader:start.window="
         active = true
         notifications.push(Object.assign($event.detail, { active: true, show: true, failed: false }))
         current = $event.detail.title ? notifications.length - 1 : current
     "
     x-on:magewire:loader:restart.window="
         if (notifications[current] !== undefined) {
             notifications[current].active = false
         }

         notifications.push(Object.assign($event.detail, { active: true, show: true, failed: false }))
         current = $event.detail.title ? notifications.length - 1 : current
     "
     x-on:magewire:loader:fail.window="
         if (notifications[current] !== undefined) {
             notifications[current].failed = true
         }
     "
     x-on:magewire:loader:stop.window="
         if (notifications[current] !== undefined) {
             notifications[current].active = false
         }

         active = false
         current = null

         let i = 0

         notifications.forEach(function (loader, index) {
             if (notifications[index].title === null || notifications[index].show === false) {
                 return
             }

             setTimeout(() => {
                 notifications[index].show = false
             }, i = i + notifications[index].failed ? 2500 : 1500)
         })
     "
     x-cloak
     role="status"
     aria-live="polite"
>
     <div class="fixed
                 top-0 left-0 right-0 bottom-0
                 w-full h-screen
                 z-40
                 overflow-hidden
                 bg-white bg-opacity-90"
          x-show="active"
          x-transition:enter="transition duration-300"
          x-transition:enter-start="opacity-0"
          x-transition:enter-end="opacity-100"
          x-transition:leave="transition duration-200"
          x-transition:leave-start="opacity-100"
          x-transition:leave-end="opacity-0"
    >
        <div class="flex flex-col justify-center items-center h-screen w-full space-y-6">
            <svg class="animate-spin h-8 w-8"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
            >
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="shadow-md" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
        </div>
    </div>

    <?= $block->getChildHtml('magewire.loader.notifications') ?>
</div>
<?php endif ?>
