<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var MagewireViewModel $magewireViewModel */

$magewireViewModel = $block->getData('view_model');
$magewireUtility = $magewireViewModel->utils()->magewire();
$magewireFragment = $magewireViewModel->utils()->fragment();
?>
<?php $script = $magewireFragment->make()->script()->start() ?>
<script>
    function magewireScript() {
        return {
            //
        };
    }

    function magewireScriptBindings() {
        return {
            'x-bind:data-update-uri'() {
                return '<?= $escaper->escapeJs($magewireUtility->getUpdateUri()) ?>';
            },
            'x-bind:data-csrf'() {
                return hyva.getFormKey()
            }
        };
    }

    <?php /* Register as Alpine component. */ ?>
    document.addEventListener('alpine:init', () => Alpine.data('magewireScript', magewireScript), { once: true })
    <?php /* Register Alpine component bindings (for optional usage). */ ?>
    document.addEventListener('alpine:init', () => Alpine.bind('magewireScriptBindings', magewireScriptBindings), { once: true });
</script>
<?php $script->end() ?>
