<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var MagewireViewModel $magewireViewModel */

$magewireViewModel = $block->getData('view_model');
$magewireUtility = $magewireViewModel->utils()->magewire();
$magewireFragment = $magewireViewModel->utils()->fragment();
?>
<?php $script = $magewireFragment->make()->script()->start() ?>
<script>
    function magewireRuntime() {
        return {
            //
        };
    }

    function magewireRuntimeBindings() {
        return {
            'x-bind:data-update-uri'() {
                return '<?= $escaper->escapeJs($magewireUtility->getUpdateUri()) ?>';
            },
            'x-bind:data-csrf'() {
                return window.MagewireUtilities.cookie.getFormKey()
            }
        };
    }

    /**
     * @deprecated Use magewireRuntime instead.
     */
    function magewireScript() {
        return magewireRuntime();
    }

    /**
     * @deprecated Use magewireRuntimeBindings instead.
     */
    function magewireScriptBindings() {
        return magewireRuntimeBindings();
    }

    <?php /* Register as Alpine component. */ ?>
    document.addEventListener('alpine:init', () => Alpine.data('magewireRuntime', magewireRuntime), { once: true })
    <?php /* Register Alpine component bindings (for optional usage). */ ?>
    document.addEventListener('alpine:init', () => Alpine.bind('magewireRuntimeBindings', magewireRuntimeBindings), { once: true });
    <?php /* Register deprecated Alpine component alias. */ ?>
    document.addEventListener('alpine:init', () => Alpine.data('magewireScript', magewireScript), { once: true })
    <?php /* Register deprecated Alpine component bindings alias. */ ?>
    document.addEventListener('alpine:init', () => Alpine.bind('magewireScriptBindings', magewireScriptBindings), { once: true });
</script>
<?php $script->end() ?>
