<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

namespace Magewirephp\Magewire\Model\View;

use Magewirephp\Magewire\Model\View\Fragment\Element;
use Magewirephp\Magewire\Support\Factory;

/**
 * Central registry for managing slot lifecycles across template areas.
 *
 * The SlotsRegistry uses a stack-based approach to track slots within nested
 * template areas (fragments, components). Each area maintains its own collection
 * of slots, with automatic counter-based naming to support multiple instances
 * of the same area type.
 *
 * Areas are tracked and untracked as templates are rendered, creating isolated
 * slot contexts that prevent naming conflicts between nested components.
 *
 * @deprecated Work in progress, do not use in production.
 */
class SlotsRegistry
{
    /** @var array<int, array<string, Slot>> $slots */
    private array $slots = [];
    /** @var array<string, int> $counters */
    private array $counters = [];
    /** @var array<string, Element> */
    private array $elements = [];

    private array $completed = [];

    private string $area = 'root-0';

    /**
     * Start tracking slots for a new area.
     *
     * Pushes a new slot collection onto the stack, initializes counters for the area,
     * and automatically creates a 'default' slot to capture the area's overall content.
     * The area identifier is generated by combining the element ID with an incremental counter.
     */
    public function track(Element $element): void
    {
        $area ??= $element->id();

        // Initialize counter for this base key if it doesn't exist.
        if (! isset($this->counters[$area])) {
            $this->counters[$area] = -1;
        }

        $this->counters[$area]++;
        // Register the latest area.
        $this->area = $area . '-' . $this->counters[$area];
        // Register the slot bag.
        $this->slots[$this->area] = [];
        // Register the current element.
        $this->elements[$this->area] = $element;

        // Register the default slot, meant for the overall content.
        $this->register('default', $element);
    }

    /**
     * Stop tracking slots for the current area and return its slots.
     *
     * Pops the current area from the stack, returning all slots that were
     * registered within it. Automatically switches context back to the
     * previous area in the stack.
     *
     * @return array<string, Slot>
     */
    public function untrack(): array
    {
        $area ??= $this->area;

        $this->completed[$area] = $this->slots[$area];
        // Get the slots for this area (not array_pop).
        $slots = $this->slots[$area] ?? [];
        // Remove this area from the slots tracking.
        unset($this->slots[$area]);
        // Set the current area to the last remaining area.
        $this->area = array_key_last($this->slots) ?? 'root-0';

        return $slots;
    }

    /**
     * Retrieve a slot by name from the current area.
     *
     * Returns null if the slot doesn't exist. Does not create the slot
     * if missing - use register() for slot creation.
     */
    public function get(string $name): Slot|null
    {
        $current = $this->slots();

        return $current[$name] ?? null;
    }

    public function default(): Slot
    {
        return $this->get('default');
    }

    /**
     * Create and register a new slot in the current area.
     *
     * Instantiates a new Slot object and adds it to the current area's
     * collection. The slot is immediately available for content updates.
     */
    public function register(string $name, Element $element): Slot
    {
        $slot = Factory::create(Slot::class, ['name' => $name, 'element' => $element]);
        $this->slots[$this->area][$slot->name()] = $slot;

        return $slot;
    }

    /**
     * Render a slot's content as a string.
     *
     * Convenience method that retrieves a slot and returns its string
     * representation, useful for direct output in templates.
     */
    public function print(string $name): string
    {
        return $this->get($name)->__toString();
    }

    /**
     * Retrieve the currently active slot in the current area.
     *
     * The "current" slot is the most recently registered one in the active area —
     * since slots register on `Slot::start()` and append to the area bag in order,
     * the last bag entry is the slot whose buffer is presently open. Returns null
     * when the current area has no slots registered yet.
     */
    public function current(): Slot|null
    {
        $slots = $this->slots();
        $key = array_key_last($slots);

        return $key === null ? null : $slots[$key];
    }

    /**
     * Retrieve a slot from the parent area.
     *
     * Walks one level up the area stack. Resolution rules:
     *
     *   1. Explicit `$name` given — look up that slot by name in the parent
     *      area; return null if missing.
     *   2. No name — return the parent area's *active* slot: the one whose
     *      output buffer is currently open. Used to detect the case where
     *      a child element is authored inside `<slot:foo>...</slot:foo>` so
     *      its render binds into `foo` rather than the area's `default`.
     *   3. No active slot — fall back to the parent area's `default` slot.
     *
     * Returns null when the current area has no parent (root area).
     */
    public function parent(string|null $name = null): Slot|null
    {
        $a = array_values($this->slots);
        $b = array_keys($this->slots);
        $c = array_search($this->area, $b, true);

        if ($c > 0) {
            return $a[$c - 1]['default'];
        }

        return null;
    }

    /**
     * Check if a slot exists in the current area.
     */
    public function exists(string $name): bool
    {
        return isset($this->slots[$this->area][$name]);
    }

    /**
     * Check if any areas are currently being tracked.
     *
     * Useful for determining if the registry has active slot contexts
     * beyond the root level.
     */
    public function hasAreas(): bool
    {
        return count($this->slots) !== 0;
    }

    /**
     * Create an immutable snapshot of the current area's slots.
     *
     * Generates a SlotSnapshot containing all slots from the current area.
     * The snapshot can be passed between template layers or stored for
     * deferred rendering.
     */
    public function snapshot(): SlotSnapshot
    {
        return Factory::create(SlotSnapshot::class, [
            'slots' => $this->slots()
        ]);
    }

    /**
     * Get the element that owns the current area.
     *
     * Returns the parent element for the currently active area, providing
     * access to element data, attributes, and properties.
     */
    public function element(): Element|null
    {
        return $this->elements[$this->area] ?? null;
    }

    /**
     * Get all slots registered in the current area.
     *
     * Returns the complete slot collection for the currently active area.
     * Used internally by other methods to access the current context.
     *
     * @return array<string, Slot>
     */
    private function slots(): array
    {
        return $this->slots[$this->area] ?? [];
    }
}
