<?php

/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

namespace Magewirephp\Magewire\Model\View;

use Magewirephp\Magewire\Model\View\Fragment\Component;
use Magewirephp\Magewire\Support\Factory;
use RuntimeException;

/**
 * Central registry for managing slot lifecycles across template areas.
 *
 * The SlotsTracker uses a stack-based approach to track slots within nested
 * template areas (fragments, components). Each area maintains its own collection
 * of slots, with automatic counter-based naming to support multiple instances
 * of the same area type.
 *
 * Areas are tracked and untracked as templates are rendered, creating isolated
 * slot contexts that prevent naming conflicts between nested components.
 *
 * @mago-expect lint:too-many-methods
 */
class SlotsRegistry
{
    /** @var array<int, array<string, Slot>> $slots */
    private array $slots = [];
    /** @var array<string, int> $counters */
    private array $counters = [];
    /** @var array<string, Component> */
    private array $components = [];

    // At the moment; only for registration purposes only.
    private array $completed = [];

    private string $area = 'root-0';

    /**
     * Start tracking slots for a new area.
     *
     * Pushes a new slot collection onto the stack, initializes counters for the area,
     * and automatically creates a 'default' slot to capture the area's overall content.
     * The area identifier is generated by combining the component ID with an incremental counter.
     */
    public function register(Component $component): void
    {
        $area ??= $component->id();

        // Initialize counter for this base key if it doesn't exist.
        $this->counters[$area] ??= -1;

        $this->counters[$area]++;
        // Register the latest area.
        $this->area = $area . '-' . $this->counters[$area];
        // Register the slot bag.
        $this->slots[$this->area] = [];
        // Register the current component.
        $this->components[$this->area] = $component;

        // Register the default slot, meant for the overall content.
        $this->add('default', $component);
    }

    /**
     * Stop tracking slots for the current area and return its slots.
     *
     * Pops the current area from the stack, returning all slots that were
     * registered within it. Automatically switches context back to the
     * previous area in the stack.
     *
     * @return array<string, Slot>
     */
    public function unregister(): array
    {
        $area ??= $this->area;

        $this->completed[$area] = $this->slots[$area];
        // Get the slots for this area (not array_pop).
        $slots = $this->slots[$area] ?? [];
        // Remove this area from the slots tracking.
        unset($this->slots[$area]);
        // Set the current area to the last remaining area.
        $this->area = array_key_last($this->slots) ?? 'root-0';

        return $slots;
    }

    /**
     * Retrieve a slot by name from the current area.
     *
     * Returns null if the slot doesn't exist. Does not create the slot
     * if missing - use register() for slot creation.
     */
    public function get(string $name): Slot|null
    {
        $current = $this->slots();

        return $current[$name] ?? null;
    }

    /**
     * Return the current area's default slot. Auto-creates it if missing —
     * called from `Component::echo()` which can't tolerate a null target,
     * so the contract is non-nullable. Throws when no area is currently
     * registered: a missing area is a programmer error, not a runtime
     * recoverable condition.
     *
     * @mago-expect lint:no-isset
     */
    public function default(): Slot
    {
        if (! isset($this->slots[$this->area]['default'])) {
            $component = $this->components[$this->area] ?? throw new RuntimeException('No area is currently registered.');

            $this->add('default', $component);
        }

        return $this->slots[$this->area]['default'];
    }

    /**
     * Get-or-create a slot of the given name in the current area.
     *
     * If a slot of `$name` already exists in the area, return it as-is so
     * its history (every prior `push()` / `append()`) survives subsequent
     * `<slot:name>` re-assignments. Only the first call for a name builds
     * a fresh Slot. The Component passed on subsequent calls is ignored —
     * the original owning Component is kept as metadata.
     *
     * @mago-expect lint:no-isset
     */
    public function add(string $name, Component $component): Slot
    {
        if (isset($this->slots[$this->area][$name])) {
            return $this->slots[$this->area][$name];
        }

        $slot = Factory::create(Slot::class, ['name' => $name, 'component' => $component]);
        $this->slots[$this->area][$slot->name()] = $slot;

        return $slot;
    }

    /**
     * Render a slot's content as a string.
     *
     * Convenience method that retrieves a slot and returns its string
     * representation, useful for direct output in templates.
     */
    public function print(string $name): string
    {
        return $this->get($name)->__toString();
    }

    /**
     * Retrieve the most recently added slot in the active area.
     *
     * Slots are appended to the area bag in source order by `add()` (called
     * from `register()` for the auto-registered `default` slot and from
     * `Fragment\Slot::start()` for explicit `<slot:*>` blocks). The last
     * entry is therefore whichever slot was most recently introduced —
     * useful when a child component needs to bind into the surrounding
     * scope without naming the target slot explicitly. Returns null when
     * the active area has no slots registered yet.
     */
    public function current(): Slot|null
    {
        $slots = $this->slots();
        $key = array_key_last($slots);

        return $key === null ? null : $slots[$key];
    }

    /**
     * Check if a slot exists in the current area.
     *
     * @mago-expect lint:no-isset
     */
    public function exists(string $name): bool
    {
        return isset($this->slots[$this->area][$name]);
    }

    /**
     * Check if any areas are currently being tracked.
     *
     * Useful for determining if the registry has active slot contexts
     * beyond the root level.
     */
    public function hasAreas(): bool
    {
        return count($this->slots) !== 0;
    }

    /**
     * Create an immutable snapshot of the current area's slots.
     *
     * Generates a SlotSnapshot containing all slots from the current area.
     * The snapshot can be passed between template layers or stored for
     * deferred rendering.
     */
    public function makeSnapshot(): SlotSnapshot
    {
        return Factory::create(SlotSnapshot::class, [
            'slots' => $this->slots()
        ]);
    }

    /**
     * Get the component that owns the current area.
     *
     * Returns the parent component for the currently active area, providing
     * access to component data, attributes, and properties.
     */
    public function component(): Component|null
    {
        return $this->components[$this->area] ?? null;
    }

    /**
     * Get all slots registered in the current area.
     *
     * Returns the complete slot collection for the currently active area.
     * Used internally by other methods to access the current context.
     *
     * @return array<string, Slot>
     */
    private function slots(): array
    {
        return $this->slots[$this->area] ?? [];
    }
}
