<?php
/**
 * Copyright © Willem Poortman 2021-present. All rights reserved.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Component\PaginationInterface;

/** @var Escaper $escaper */
/** @var Template $block */

/** @var PaginationInterface $pagination */
$pagination = $block->getComponent();

$paginationBtnCssClasses = "p-2 rounded-sm border border-gray-300 hover:bg-primary hover:text-on-primary cursor-pointer disabled:cursor-not-allowed disabled:bg-transparent disabled:text-gray-400";
?>
<div>
    <?php if ($pagination->hasPages()): ?>
    <div class="flex gap-1 items-center">
        <button
            type="button"
            class="<?= $escaper->escapeHtmlAttr($paginationBtnCssClasses) ?>"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Previous page')); ?>"
            <?php if ($pagination->onFirstPage()): ?>
            disabled
            <?php else: ?>
            wire:click="toPreviousPage"
            <?php endif; ?>
        >
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="rtl:rotate-180"><path d="m11 17-5-5 5-5"/><path d="m18 17-5-5 5-5"/></svg>
        </button>

        <button
            type="button"
            class="<?= $escaper->escapeHtmlAttr($paginationBtnCssClasses) ?>"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Next page')); ?>"
            <?php if ($pagination->hasMorePages()): ?>
            wire:click="toNextPage"
            <?php else: ?>
            disabled
            <?php endif; ?>
        >
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="rtl:rotate-180"><path d="m6 17 5-5-5-5"/><path d="m13 17 5-5-5-5"/></svg>
        </button>
    </div>
    <?php endif; ?>
</div>
