<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$blockLoaderIcon = $block->getChildBlock('loader') ?>
<div class="magewire-notifier-activity-state" x-show="notification.loader.active">
    <?php /* Stack items vertically to prevent layout shifting when hiding or disappearing, ensuring consistent visual layout. */ ?>
    <?php if ($blockLoaderIcon): ?>
        <div x-show="notification.state">
            <?= $blockLoaderIcon->toHtml() ?>
        </div>
    <?php endif ?>
</div>
