name: 'Mago'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  mago:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Mago
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://carthage.software/mago.sh | bash -s -- --no-verify
          mago --version

      - name: Strip external includes from mago.toml
        run: sed -i '/^includes\s*=/d' mago.toml

      - name: Mago lint
        run: mago lint --reporting-format=github

      - name: Mago analyze
        run: mago analyze --reporting-format=github

      - name: Mago format check
        run: mago format --check