name: 'Portman Build'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'portman/**'
      - 'src/**'
      - 'lib/**'

permissions:
  contents: write

jobs:

  portman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.head_ref || github.event.pull_request.head.sha }}
          token: ${{ secrets.MY_TOKEN || github.token }}
          persist-credentials: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Configure public Magento mirror
        run: composer config --global repositories.magento composer https://mirror.mage-os.org/

      - name: Install composer
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-scripts"

      - name: Portman build
        run: ./vendor/bin/portman build

      - name: Verify Portman build is committed
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          git add --intent-to-add --all
          git diff --exit-code

      - name: Commit Portman build
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(portman) build'
