<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var MagewireViewModel $magewireViewModel */
/** @var AbstractBlock|false $notificationsBeforeBlock */
/** @var AbstractBlock|false $notificationsAfterBlock */

/** @purge: bottom-4, left-6, top-4, right-6 */

$notificationsBeforeBlock = $block->getChildBlock('notification.before');
$notificationsAfterBlock = $block->getChildBlock('notification.after');

$magewireViewModel = $block->getData('view_model');
$templateUtil = $magewireViewModel->utils()->template();
$layoutUtil = $magewireViewModel->utils()->layout();
?>
<?= $templateUtil->echoCodeComment('notifier', false, 'UI Component') ?>
<div
    class="magewire-notifier"
    x-data="magewireNotifier"
    x-bind="magewireNotifierBindings"
>
    <template x-for="notification in notifications">
        <div
            class="magewire-notifier__notification"
            aria-busy="true"
            aria-label="off"
            role="status"
            x-show="notification.active"
            x-transition.duration.500ms
            x-bind="bindings.notification.item"
        >
            <div class="magewire-notifier__notification-content">
                <?php if ($layoutUtil->canContainerizeBlock($notificationsBeforeBlock)): ?>
                <div class="magewire-notifier__notification-before">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsBeforeBlock) ?>
                </div>
                <?php endif ?>

                <div>
                    <div class="magewire-notifier__notification-title"
                         x-text="notification.title"
                         x-show="notification.title"
                    >
                        <!-- Notification title placeholder. -->
                    </div>

                    <p class="magewire-notifier__notification-message"
                       x-text="notification.message"
                       x-show="notification.message"
                    >
                        <!-- Notification message placeholder. -->
                    </p>
                </div>

                <?php if ($layoutUtil->canContainerizeBlock($notificationsAfterBlock)): ?>
                <div class="magewire-notifier__notification-after">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsAfterBlock) ?>
                </div>
                <?php endif ?>
            </div>
        </div>
    </template>
</div>
