<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var MagewireViewModel $magewireViewModel */
/** @var AbstractBlock|false $notificationsBeforeBlock */
/** @var AbstractBlock|false $notificationsAfterBlock */

$notificationsBeforeBlock = $block->getChildBlock('notification.before');
$notificationsAfterBlock = $block->getChildBlock('notification.after');

$magewireViewModel = $block->getData('view_model');
$templateUtil = $magewireViewModel->utils()->template();
$layoutUtil = $magewireViewModel->utils()->layout();
?>
<?= $templateUtil->echoCodeComment('notifier', false, 'UI Component') ?>
<div x-data="magewireNotifier" x-bind="magewireNotifierBindings">
    <template x-for="notification in notifications">
        <div
            aria-busy="true"
            aria-label="off"
            role="status"
            x-show="notification.active"
            x-transition:enter.duration.400ms
            x-transition:leave.duration.100ms
            x-bind="bindings.notification.item.root"
        >
            <?php if ($layoutUtil->canContainerizeBlock($notificationsBeforeBlock)): ?>
                <div class="magewire-notifier-before">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsBeforeBlock) ?>
                </div>
            <?php endif ?>

            <div class="magewire-notifier-body">
                <p class="magewire-notifier-title" x-show="notification.title">
                    <strong x-text="notification.title">
                        <!-- Notification title placeholder. -->
                    </strong>
                </p>

                <p class="magewire-notifier-message"
                   x-text="notification.message"
                   x-show="notification.message"
                >
                    <!-- Notification message placeholder. -->
                </p>
            </div>

            <?php if ($layoutUtil->canContainerizeBlock($notificationsAfterBlock)): ?>
                <div class="magewire-notifier-after">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsAfterBlock) ?>
                </div>
            <?php endif ?>
        </div>
    </template>
</div>
