<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var MagewireViewModel $magewireViewModel */
/** @var AbstractBlock|false $notificationsBeforeBlock */
/** @var AbstractBlock|false $notificationsAfterBlock */

/** @purge: bottom-4, left-6, top-4, right-6 */

$notificationsBeforeBlock = $block->getChildBlock('notification.before');
$notificationsAfterBlock = $block->getChildBlock('notification.after');

$magewireViewModel = $block->getData('view_model');
$templateUtil = $magewireViewModel->utils()->template();
$layoutUtil = $magewireViewModel->utils()->layout();
?>
<?= $templateUtil->echoCodeComment('notifier', false, 'UI Component') ?>
<div
    class="space-y-2 z-50 w-full fixed bottom-4 left-6 md:max-w-xs ml-2 mb-2 flex flex-col"
    x-data="magewireNotifier"
    x-bind="magewireNotifierBindings"
>
    <template x-for="notification in notifications">
        <div
            class="magewire-notification pointer-events-auto relative w-full py-3 px-5 max-w-sm rounded-lg drop-shadow-lg font-bold bg-white"
            aria-busy="true"
            aria-label="off"
            role="status"
            x-show="notification.active"
            x-transition.duration.500ms
            x-bind="bindings.notification.wrapper"
        >
            <div class="flex items-center justify-between">
                <?php if ($layoutUtil->canContainerizeBlock($notificationsBeforeBlock)): ?>
                <div class="magewire-notification-before flex items-center space-x-3">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsBeforeBlock) ?>
                </div>
                <?php endif ?>

                <div>
                    <div x-text="notification.title"
                         x-show="notification.title"
                         x-bind="bindings.notification.title"
                    >
                        <!-- Notification title placeholder. -->
                    </div>

                    <p x-text="notification.text"
                       x-show="notification.text"
                       x-bind="bindings.notification.text"
                    >
                        <!-- Notification text placeholder. -->
                    </p>
                </div>

                <?php if ($layoutUtil->canContainerizeBlock($notificationsAfterBlock)): ?>
                <div class="magewire-notification-after flex items-center space-x-3">
                    <?= $layoutUtil->renderBlockAsContainer($notificationsAfterBlock) ?>
                </div>
                <?php endif ?>
            </div>
        </div>
    </template>
</div>
