<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\ViewModel\Magewire as MagewireViewModel;

/** @var Template $block */
/** @var MagewireViewModel $magewireViewModel */

$magewireViewModel = $block->getData('view_model');
$magewireFragment = $magewireViewModel->utils()->fragment();
?>
<?php $script = $magewireFragment->make()->script()->start() ?>
<script>
    (() => {
        'use strict';

        const magewireBcEventsMapping = [
            { from: 'livewire:init', to: 'magewire:init', legacy: false },
            { from: 'livewire:initialized', to: 'magewire:initialized', legacy: false },

            <?php /* To support legacy V1 events. */ ?>
            { from: 'magewire:init', to: 'magewire:load', legacy: true },
            { from: 'magewire:initialized', to: 'magewire:available', legacy: true }
        ];

        magewireBcEventsMapping.forEach(({ from, to, legacy }) => {
            document.addEventListener(from, original => {
                const details = { ...original.detail };
                const event = to.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

                document.dispatchEvent(new CustomEvent(event, {
                    detail: details,
                    bubbles: original.bubbles,
                    cancelable: original.cancelable
                }));
            });
        });
    })();
</script>
<?php $script->end() ?>
